---
- name: Deployer of project
  hosts: all
  become: yes
  tasks:

    - name: Install dependences
      apt:
        update_cache: yes
        pkg:
          - python3.8
          - python3.8-venv
          - python3-pip
          - git
          - firefox

    - name: Download geckodriver
      get_url:
        url: https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
        dest: /home/main/geckodriver-v0.27.0-linux64.tar.gz

    - name: Untar geckodriver
      unarchive:
        src: /home/main/geckodriver-v0.27.0-linux64.tar.gz
        dest: /usr/bin/
        remote_src: yes

    - name: Remove geckodriver.tar
      file:
        path: /home/main/geckodriver-v0.27.0-linux64.tar.gz
        state: absent

    - name: Install virtualenv via pip
      pip:
        name: virtualenv
        executable: pip3

    - name: Install latest setuptools and pip
      pip:
        name:
          - setuptools
          - pip
          - wheel
        state: latest
        virtualenv: /home/main/venvs/nalog


    - name: Clone project
      git:
        repo: 'https://github.com/ponomarevkonst/nalog_scrapper'
        dest: /home/main/nalog_scrapper
        clone: yes
        update: yes

    - name: Install requirements
      pip:
        requirements: /home/main/nalog_scrapper/requirments.txt
        virtualenv: /home/main/venvs/nalog

    - name: Allow all access to tcp port 5000
      ufw:
        rule: allow
        port: '5000'
        proto: tcp

    - name: Run server #fix it somehow
      command:
        cmd:  screen /home/main/venvs/nalog/bin/python3 /home/main/nalog_scrapper/server.py
